# ==== ETAPA 1: Build de Vite ====
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ==== ETAPA 2: Servir con Nginx ====
FROM nginx:stable-alpine

# Elimina contenido por defecto
RUN rm -rf /usr/share/nginx/html/*

# Copia el build generado por Vite
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
